declare const styles: {
    splash: string;
    message: string;
    'fa-spinner': string;
    'page-host': string;
    'navbar-nav': string;
    loader: string;
    pictureDetail: string;
    'au-enter-active': string;
    fadeInRight: string;
    'au-stagger': string;
    'card-container': string;
    'au-enter': string;
    fadeIn: string;
    card: string;
    content: string;
    name: string;
    'header-bg': string;
    avatar: string;
};
export default styles;
